### ISSUE TITLE
Caravan "broke" after trading with friend's settlement

### ISSUE THREAD

**Issue by Cryazka** [RimworldTogether/Rimworld-Together#106]
![изображение](https://github.com/RimworldTogether/Rimworld-Together/assets/62844595/41ccf3e8-e5b5-4fe5-90c7-471485b48ce7)
    [Player.log](https://github.com/user-attachments/files/15526631/Player.log)
    
  Caravan "broke" after trading with friend's settlement
  This is not first time of trading. Before, everything was fine.

  Mods:
  - brrainz.harmony
  - Ludeon.RimWorld
  - Ludeon.RimWorld.Royalty
  - Ludeon.RimWorld.Ideology
  - Ludeon.RimWorld.Biotech
  - Ludeon.RimWorld.Anomaly
  - UnlimitedHugs.HugsLib
  - nova.rimworldtogether
  - Unon.NoBurnMetal
  - brrainz.cameraplus
  - Fuu.BloodAnimations
  - UnlimitedHugs.DefensivePositions

**Comment by Byte-Nova** [comment]
Hello there, the logs don't suggest it's an issue regarding our mod, could you double check if this happens during a single player playthrough to gather more clues?

**Comment by Cryazka** [comment]
Hello. It happened once while my friend was online. I dont have any backups so then I enter save in single player its "broken" too.
So, I dont think I have anything to help with. Will make backups and report if this happen again
