### ISSUE TITLE
Server can't load mod, The following modes are conflicting with the server.

### ISSUE THREAD

**Issue by kazhu233** [RimworldTogether/Rimworld-Together#134]
【My English is so poor, so I used machine translation. Please understand.】
Today, when I was configuring mods for Rimworld Together, I found that the server couldn't load the mods.  So, I reinstalled the game and updated the mods, but it still couldn't load them. Then I found the problem in the "About.xml" file of the mod that couldn't be loaded.
After accidentally deleting a "<", I noticed that the server read the file and returned an error.   So, I compared this file with the "About.xml" files of other mods that could be read normally, and found that the unreadable "About.xml" used "<modMetaData></modMetaData>", while the readable ones used "<ModMetaData></ModMetaData>".
So, I changed it to start with a capital letter, and then the mod could be read normally.
Maybe could consider fixing this?
![1](https://github.com/user-attachments/assets/a6d6b4b7-e498-4bd1-857f-7622930d5776)
![2](https://github.com/user-attachments/assets/148ad7b3-2e6c-4ec1-bc51-c3537e9b9e4d)
![3](https://github.com/user-attachments/assets/bbf11b49-bcde-47b9-af8e-ff4ec360904d)
![4](https://github.com/user-attachments/assets/f33a1d98-9c91-4d90-8a92-20f5af615151)
![5](https://github.com/user-attachments/assets/e3ac7521-c346-4544-b889-10bfbc5c7c55)
![6](https://github.com/user-attachments/assets/f73dbe41-1cea-4a8c-830e-43521d0232ca)

**Comment by Haeherfeder** [comment]
is internally known (and is in the not yet published guide indirectly mentioned)

if i remember correctly, someone on the discord said yesterday, that they will look into it, but not sure
