### ISSUE TITLE
🐛 [BUG] - <Default Event list... WHAT?>

### ISSUE THREAD

**Issue by SimobiSirOP** [RimworldTogether/Rimworld-Together#161]
### Description

Why Archonexus Victory in default event list?
(Event that gives access to archonexus place to end the game)

It's just stupid...

### OS

Windows

### Reproduction steps

```bash
1. Go to 'World map'
2. Click on 'Event'
3. Scroll down to 'Archonexus Victory'
4. See WTH
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

### Client logs

```bash
Doesn't require
```

### Server logs

```bash
Doesn't require
```

**Comment by Byte-Nova** [comment]
Event can be disabled by the server owners, we might as well just have it disabled by default granted what it does. Thanks for the heads up :+1:
