### ISSUE TITLE
apply filtering to ingame -> discord chat messages

### ISSUE THREAD

**Issue by ghost** [RimworldTogether/Rimworld-Together#200]
the chat relay should apply some filters to the message, such as removing or disabiling @ everyone, @ here, @ role pings.

an easy way to do that is to find any word that starts with a @ and applying a space between the word and the @.
currently the way the code is structured, if the bot has sufficient permissions, and someone sends a `@everyone` message. it will ping everyone.

**Comment by nightred** [comment]
This is intended behavior, please limit the bots permissions in discord if you do not want it triggering @ events.

Personally I see this as intended so that someone can ping users not connected to the game to interact or be flagged.
