### ISSUE TITLE
Debian (Linux) install guide?

### ISSUE THREAD

**Issue by moda84** [RimworldTogether/Rimworld-Together#202]
Hello.
I cant join Discord server, but I need help.
How to install RimWorld Together on Debian/Linux OS? (I not found guide for Linux)
In page of releases has ZIP archive, but inside it GameServer.FILE and it not open how archive, not run from bash and idk what do for install it.
Please help. ♥

**Comment by Byte-Nova** [comment]
You should be able to open the GameServer file by calling it through a terminal using "./GameServer" in the same folder. You might need to give it read/write permissions depending on your system
