### ISSUE TITLE
🐛 [BUG] - Server crashes when running via systemd

### ISSUE THREAD

**Issue by Tallyrald** [RimworldTogether/Rimworld-Together#203]
### Description

I'm hosting several applications on my server and now that I'm trying to set up Rimworld Together, it seems that the server doesn't like being started via systemd and crashes when trying to print to console.

### OS

Linux

### Reproduction steps

1. Create the following systemd unit file: ```/lib/systemd/system/rimworld-server.service```
```
[Unit]

Description=start and stop the rimworld-server



[Service]

WorkingDirectory=/usr/games/rimworld

User=rimworld

Group=rimworld

Restart=on-failure

RestartSec=120

ExecStart=/usr/games/rimworld/GameServer


[Install]

WantedBy=multi-user.target
```

2. Enable the service ```enable rimworld-server.service```
3. Check the journal for the error ```journalctl -u rimworld-server.service```

### Client logs

```bash
No client log
```

### Server logs

```bash
Dec 18 19:32:24 nextcloud systemd[1]: Started start and stop the rimworld-server.
Dec 18 19:32:24 nextcloud GameServer[2182847]: Unhandled exception. System.Exception: Logger encountered an error. This should never happen
Dec 18 19:32:24 nextcloud GameServer[2182847]:    at GameServer.Logger.WriteToConsole(String text, LogMode mode, LogImportanceMode importance, Boolean writeToLogs)
Dec 18 19:32:24 nextcloud GameServer[2182847]:    at GameServer.Main_.SetCulture()
Dec 18 19:32:24 nextcloud GameServer[2182847]:    at GameServer.Main_.Main()
Dec 18 19:32:24 nextcloud systemd[1]: rimworld-server.service: Main process exited, code=dumped, status=6/ABRT
Dec 18 19:32:24 nextcloud systemd[1]: rimworld-server.service: Failed with result 'core-dump'.
```

**Comment by cirune** [comment]
Does the rimworld user have r/w privileges to the /usr/game/rimworld folder?
Normally it doesn't and the GameServer executable needs to be able to write in it's own folder.

You could try to change the working directory.

**Comment by Tallyrald** [comment]
You are right it was a permissions issue. What happened is that I launched the executable as root while testing and therefore all the auto-created folders and files were owned by root, even though I set up a new user and group for the server.
Solution was to change the owner for all directories and files. Thanks for the help!
