### ISSUE TITLE
On the synchronization issue of planetary mod factions

### ISSUE THREAD

**Issue by MichaelMyers1743** [RimworldTogether/Rimworld-Together#23]
How can I load some mod factions so that my friends and the factions I see on the planet are the same?The current issue is that even if I first enter the server to generate the planet and save it, my friend will still see different factions assigned to different locations, and even the names of each faction are different, which confuses me.

**Comment by AnauNaga** [comment]
Thats because right now, as a bandaid, we are generating factions for the same seed and hoping its the same for both players.
For vanilla, Its usually ends up being the same, but when you add mods it can end up being different. 
For the most part, it won't affect your game.

Making factions synchronize between different clients is something we are actively working on

**Comment by MichaelMyers1743** [comment]
> 那是因为现在，作为创可贴，我们正在从同一种子中产生派系，并希望这对两个玩家来说都是一样的。对于香草来说，它通常最终是相同的，但是当您添加模组时，它最终可能会有所不同。在大多数情况下，它不会影响您的游戏。
> 
> 使派系在不同客户之间同步是我们正在积极努力的事情

I'm glad to see your reply, so what you mean is that this issue has not been resolved yet, right? I thought version 1.3 had already completed this issue, but anyway, thank you very much for your reply.

**Comment by AnauNaga** [comment]
1.3 was supposed to fix that, but I think a lot of people were experiencing problems, so we had to undo our changes

**Comment by MichaelMyers1743** [comment]
> 那是因为现在，作为创可贴，我们正在从同一种子中产生派系，并希望这对两个玩家来说都是一样的。对于香草来说，它通常最终是相同的，但是当您添加模组时，它最终可能会有所不同。在大多数情况下，它不会影响您的游戏。
> 
> 使派系在不同客户之间同步是我们正在积极努力的事情

But will the current asynchronous issue cause other players to see me building bases on some of the colonies they see?Will this cause unnecessary trouble? For example, problems like file collapse? Should I avoid such issues until the synchronization issue is resolved?

**Comment by MichaelMyers1743** [comment]
> 1.3 应该可以解决这个问题，但我认为很多人都遇到了问题，所以我们不得不撤消我们的更改

Unfortunately, I tested this issue in version 1.3. Specifically, after I finished loading the map, I saved the current world (but the server did not save it, I just exited and saved it on the client). Then when my friend came in, he was completely different from the planet I saw. We only added an imperial faction mod for testing purposes. Have I encountered any issues in some aspects of testing? Should I save and reload the server upon successful loading?

**Comment by AnauNaga** [comment]
I believe thats why we had to revert the changes we made.
I wouldn't worry too much about the asynchronous planet right now unless you have a server with a few dozen settlements.

**Comment by MichaelMyers1743** [comment]
> 我相信这就是为什么我们必须恢复我们所做的更改。我现在不会太担心异步星球，除非你有一个有几十个玩家定居点的服务器。

Yes, that's my problem because I'm playing this server with a lot of people, about 10 people, and we're having a headache with this issue.Anyway, thank you for your reply. I look forward to achieving full synchronization in the future. By the way, can the latest version of mod allow two people to control a colony?

**Comment by AnauNaga** [comment]
Not yet.

**Comment by MichaelMyers1743** [comment]
> 还没有。

And have the basic synchronization issues not been updated?

**Comment by Smithor** [comment]
In my experience with our use of the server, you can resolve most of the factions not matching up by making sure you have a similar load-order.

This might be something to consider in the future, having a "recommended" mod load-order from the server that pops up as a notice if your list differs (That you can then click 'ok' on to ignore, or go back and adjust). As ModManager modlists can be transferred just by a string, that wouldn't be too difficult data wise; only part I'm not sure about is the integration with ModManager. (This is how we did it with us, we went through the mods together, split and ordered them, then passed out the string for the known modlist to other players)

Still won't be full-sync necessarily, but can at least be closer. Also can help avoid some of those different modlist side-issues. Having a known stable list could be handy.

**Comment by MichaelMyers1743** [comment]
> 根据我使用服务器的经验，您可以通过确保具有相似的加载顺序来解决大多数不匹配的派系。
> 
> 这可能是将来要考虑的事情，如果您的列表不同，则从服务器获得“推荐”的 mod 加载顺序，该顺序会弹出通知（然后您可以单击“确定”忽略，或返回并进行调整）。由于 ModManager modlist 可以通过字符串传输，因此在数据方面不会太困难;唯一我不确定的部分是与 ModManager 的集成。（这就是我们的做法，我们一起浏览模组，拆分并排序它们，然后将已知模组列表的字符串传递给其他玩家）
> 
> 仍然不一定是完全同步的，但至少可以更接近。还可以帮助避免一些不同的模组列表附带问题。拥有一个已知的稳定列表可能会很方便。

Thank you very much for your answer! It is strange that there is a certain probability that the servers currently running will not synchronize with the factions of Rimworld itself. When I gave up, I added some mods from other factions, but unexpectedly they synchronized, which I cannot understand. Therefore, I am wondering if your solution can increase the probability of synchronization problems. Currently, this seems to be completely random
