### ISSUE TITLE
Package drops lead to disconnect on Save sync + Save button request 

### ISSUE THREAD

**Issue by Ione15** [RimworldTogether/Rimworld-Together#54]
As per titel more explained:

Sometime the client appears to loose the connection which isn't noticed until the next Save period on which the client will show lost server connection. (Didn't really debug, suspecting package loss of Tcp package and perhaps no keep alive packages ?)

Additionally it would be very useful to add a manual save button which doesn't quit to menu, configurable to be available opt in Server Side.

**Comment by dlh2** [comment]
I can agree with this problem, we've been playing two days, and this makes us lose progress, we've seen we can change the autosave from 3 days to 1 day in the client, so at least we don't lose so much progress
