### ISSUE TITLE
Player Raids of non-existing Players

### ISSUE THREAD

**Issue by Ione15** [RimworldTogether/Rimworld-Together#55]
Occasionally when nobody is online(except oneself)there is an alert about a player raid but the colonists appearing are of no players faction Nor xenotype/ideology .

If I can somehow know how to provide additional information please let me know (ie logs etc)

**Comment by Byte-Nova** [comment]
Hello there, If you mean that you receive raids from pawns that are part of the "OnlinePlayer" factions, it's not an error to be concerned about. It's a game limitation that the mod has right now because online factions are treated as normal ones, and can attack.

**Comment by Ione15** [comment]
Very unfortunate.
Is there a fix in sight or will this be left as nofix?

**Comment by Byte-Nova** [comment]
There might be a fix that we don't know of yet. If it would involved changing completely the way they are treated as factions I would assume it would be *very* low priority.
