### ISSUE TITLE
Server Modularity & Mod Addons

### ISSUE THREAD

**Issue by LubieKakao1212** [RimworldTogether/Rimworld-Together#76]
I have been recently using this mod, and been thinking about current and potential compatibility issues, and potential improvements.
So, if you were to add everything to the server code it would get extremely bloated with features that not everyone would benefit from.

My suggested solution is to make the server modular i.e. split is into several dlls which could be mixed and matched for the required feature set. To ease server owners with the setup there could also be an installer or some kind of setup tool and a central "addon" repository. This would also allow for more fancy server features like player quests or sites to be optional.

Also I can help with implementing this.

**Comment by ThePennitentOne** [comment]
Great idea, server side mods would help a lot with getting the server more compatible with everyone’s personal preferences

**Comment by FredyJabe** [comment]
+1 on that!

**Comment by AnauNaga** [comment]
The actual server takes up about 0.2% of the size of the exe file (The exe is 66MB and the server code is about 154 KB). I can assure you that making the server full of useful features won't be an issue. Most of what we add to the server is only QoL, packet handling, or added commands like the force save all command thats in review.

**Comment by ThePennitentOne** [comment]
I see, but the ability to make addons/server side mods would still be greatly appreciated, (just makes adding  specific mod compat much easier)

**Comment by AnauNaga** [comment]
I agree, I just meant file size isn't an issue when adding features. We can let it be plentiful

**Comment by LubieKakao1212** [comment]
#95 good to see there is some work done regarding this
