### ISSUE TITLE
Main branch is out of date compared to released 1.5.0 compiled version

### ISSUE THREAD

**Issue by matthewes1** [RimworldTogether/Rimworld-Together#82]
I made a thread on discord but opening this here as well. The main branch is behind by a few commits compared to the released compiled version. The commit that the compiled release is 60f9db6. I made a branch on my fork up to the proper commit.

**Comment by Byte-Nova** [comment]
Fixed, the stable branch should now be targeting the latest release version. Thanks for the insight!
