### ISSUE TITLE
[REQUEST] Server Domain Connections 

### ISSUE THREAD

**Issue by ArxKnight** [RimworldTogether/Rimworld-Together#96]
Hi, I have been looking through how to set up this server best for some friends to join one world together and the only options for hosting are Local, Port Forward and VPN Tunneling. 

Could we get domain resolving added to this mod so that people like me who have a dynamic IP address can get players to connect with "subdomain.domain.com" rather than using a public IP address and port "89.158.64.8:25555"?

If I am overlooking something then please feel free to correct me however, I cannot see any support currently for using subdomains in order to allow players to connect over WAN.

Link to current connection methods - https://rimworld-together.fandom.com/wiki/Going_public

**Comment by AnauNaga** [comment]
well. We have servers that currently use a domain name instead of an ip address. Specifically Claytonia Gaming comes to mind

**Comment by FredyJabe** [comment]
Can confirm that connecting with domain instead of IP works, my players use my domain to connect with no issue.

**Comment by ArxKnight** [comment]
Hi,

thanks for your quick replies @FredyJabe & @AnauNaga

Would you be able to point me in the right direction of setting this up as I have set up the subdomain, pointed it at the server using NGINX and made sure all the correct ports are open. The server is accessible via the public IP and port but via the domain, it doesn't seem to work for some reason.

Here is a screenshot of how I am entering it into the game - 
![Untitlawdartyhwed](https://github.com/RimworldTogether/Rimworld-Together/assets/19707286/5058063d-2ac9-401e-8f54-2192268719af)

The server is both accessible via local connection 192.168.... as well as the public WAN IP. Just seems to be the domain that is the issue.

Any and all help is much appreciated. :)

**Comment by FredyJabe** [comment]
Then your domain is not setup well, as everyone connect to my server with the domain itself with no issue and I haven't changed anything in the configs for it to work

**Comment by davidfleming** [comment]
Hi @LostkingZ 

I recommend using an online dns lookup tool and verifying that the DNS address publicly resolves to the IP address you are expecting.

https://www.google.com/search?q=dns+lookup

**Comment by ArxKnight** [comment]
Thanks, I resolved the domain issue. Turns out that if you're using Cloudflare for your domain you need to disable the proxy as it won't work through a proxy.
