### ISSUE TITLE
World Map Attributes Not Synced

### ISSUE THREAD

**Issue by kodypeterson** [RimworldTogether/Rimworld-Together#98]
The world map (roads, rivers, faction locations, biomes) are not synced across players.

**Comment by Byte-Nova** [comment]
Hey there, currently some features may not be synced correctly for a variety of reasons that might include (for the most part) something going on with the mod list you might be using. It might be something else, just saying that is the most common reason with users and we can't check for anything else without any logs.

World generation is likely receiving an overhaul either in the next version or the one to come after that (in #94), hopefully fixing this issue for good.
